### ISSUE TITLE
self signed certificates break the script.

### ISSUE THREAD

**Issue by PI-Victor** [ereslibre/build-caasp-iso#2] opened 2017-04-10 10:23 UTC
you have to manually do `osc co Devel:CASP:1.0:ControllerNode` and permanently accept the self signed certificates before the script will work. unfortunately the script doesn't tell you that.

anyway to have a log dump of the output from the `osc co` wrapper https://github.com/ereslibre/build-caasp-iso/blob/master/build-caasp-iso.rb#L96 ?
or have a --insecure for `osc co` (i didn't find that so far.)

**Comment by ereslibre** [comment] 2017-04-10 20:09
I cannot reproduce the problem, can I get a way to reproduce it once that I have it working? I removed `~/.oscrc` and all `osc` related configuration/cookies, but I cannot reproduce this self signed certificates problem (were you missing our internal CA installation maybe?)

**Comment by ereslibre** [comment] 2017-04-10 20:13
NVM, I could reproduce it right now.

**Comment by ereslibre** [comment] 2017-04-10 20:22
Can this be considered as fixed with the following output?

```
ruby build-caasp-iso.rb
> Requesting sudo
> Checking out CaaSP DVD product... failed (retcode: pid 20894 exit 1)
   > command: osc co Devel:CASP:1.0:ControllerNode/_product:CAASP-dvd5-DVD-x86_64
   > stdout:
     | Username:
   > stderr:
     | Your user account / password are not configured yet.
     | You will be asked for them below, and they will be stored in
     | /home/ereslibre/.oscrc for future use.
     | 
     | Creating osc configuration file /home/ereslibre/.oscrc ...
     | aborted.
build-caasp-iso.rb:135:in `read': No such file or directory @ rb_sysopen - /home/ereslibre/projects/suse/build-caasp-iso/Devel:CASP:1.0:ControllerNode/_product:CAASP-dvd5-DVD-x86_64/CAASP-dvd5-DVD-x86_64.kiwi (Errno::ENOENT)
        from build-caasp-iso.rb:135:in `patch_kiwi'
        from build-caasp-iso.rb:193:in `build_iso'
        from build-caasp-iso.rb:204:in `<main>'
```

**Closed as completed** 2017-04-10 20:30 UTC

**Comment by PI-Victor** [comment] 2017-04-10 21:52
that was the exact output i was getting which was cryptic, but i guess it will do. i don't think you should hit this if you have the suse-ca certificates installed. still better :+1:
